// Generated by https://quicktype.io

export interface GlobalResponse {
  default_sets: number[];
  sets: { [key: string]: Set };
  users: Users;
}

export interface ChannelResponse {
  sets: { [key: string]: Set };
  room: Room;
}

export interface Room {
  _id: number;
  twitch_id: number;
  youtube_id: null;
  id: string;
  is_group: boolean;
  display_name: string;
  set: number;
  moderator_badge: null;
  vip_badge: null;
  mod_urls: null;
  user_badges: UserBadges;
  user_badge_ids: UserBadgeIDS;
  css: null;
}

export interface UserBadgeIDS {
  '2': number[];
}

export interface UserBadges {
  '2': string[];
}

export interface Set {
  id: number;
  _type: number;
  icon: null;
  title: string;
  css: null;
  emoticons: Emoticon[];
}

export interface Emoticon {
  id: number;
  name: string;
  height: number;
  width: number;
  public: boolean;
  hidden: boolean;
  modifier: boolean;
  modifier_flags: number;
  offset: null;
  margins: null;
  css: null;
  owner: Owner;
  artist: null;
  urls: { [key: string]: string };
  status: number;
  usage_count: number;
  created_at: string;
  last_updated: null | string;
}

export interface Owner {
  _id: number;
  name: Name;
  display_name: DisplayName;
}

export enum DisplayName {
  Dansalvato = 'dansalvato',
  SirStendec = 'SirStendec',
  Wolsk = 'Wolsk',
}

export enum Name {
  Dansalvato = 'dansalvato',
  Sirstendec = 'sirstendec',
  Wolsk = 'wolsk',
}

export interface Users {
  '1532818': string[];
}
