// Generated by https://quicktype.io

export type GlobalResponse = EmoteSet;

export interface ChannelResponse {
  id: string;
  platform: string;
  username: string;
  display_name: string;
  linked_at: number;
  emote_capacity: number;
  emote_set_id: null;
  emote_set: EmoteSet;
  user: User;
}

export interface EmoteSet {
  id: ID;
  name: string;
  flags: number;
  tags: unknown[];
  immutable: boolean;
  privileged: boolean;
  emotes: Emote[];
  emote_count: number;
  capacity: number;
  owner: Owner | null;
}

export interface Emote {
  id: string;
  name: string;
  flags: number;
  timestamp: number;
  actor_id: ID;
  data: Data;
}

export enum ID {
  The60E754A2484Ebd628Be5Fa3E = '60e754a2484ebd628be5fa3e',
  The61085207Adcc3D4386150D73 = '61085207adcc3d4386150d73',
  The61Ee5B6C1A1B2A6E73253Dd5 = '61ee5b6c1a1b2a6e73253dd5',
}

export interface Data {
  id: string;
  name: string;
  flags: number;
  lifecycle: number;
  state: State[];
  listed: boolean;
  animated: boolean;
  owner: Owner;
  host: Host;
  tags?: string[];
}

export interface Host {
  url: string;
  files: File[];
}

export interface File {
  name: Name;
  static_name: StaticName;
  width: number;
  height: number;
  frame_count: number;
  size: number;
  format: Format;
}

export enum Format {
  Avif = 'AVIF',
  Webp = 'WEBP',
}

export enum Name {
  The1XAvif = '1x.avif',
  The1XWebp = '1x.webp',
  The2XAvif = '2x.avif',
  The2XWebp = '2x.webp',
  The3XAvif = '3x.avif',
  The3XWebp = '3x.webp',
  The4XAvif = '4x.avif',
  The4XWebp = '4x.webp',
}

export enum StaticName {
  The1XStaticAvif = '1x_static.avif',
  The1XStaticWebp = '1x_static.webp',
  The2XStaticAvif = '2x_static.avif',
  The2XStaticWebp = '2x_static.webp',
  The3XStaticAvif = '3x_static.avif',
  The3XStaticWebp = '3x_static.webp',
  The4XStaticAvif = '4x_static.avif',
  The4XStaticWebp = '4x_static.webp',
}

export interface Owner {
  id: string;
  username: string;
  display_name: string;
  avatar_url: string;
  style: Style;
  roles: Role[];
}

export enum Role {
  The60724F65E93D828Bf8858789 = '60724f65e93d828bf8858789',
  The6076A86B09A4C63A38Ebe801 = '6076a86b09a4c63a38ebe801',
  The6076A99409A4C63A38Ebe802 = '6076a99409a4c63a38ebe802',
  The60B3F1Ea886E63449C5263B1 = '60b3f1ea886e63449c5263b1',
  The6102002Eab1Aa12Bf648Cfcd = '6102002eab1aa12bf648cfcd',
  The62B48Deb791A15A25C2A0354 = '62b48deb791a15a25c2a0354',
}

export interface Style {
  color?: number;
}

export enum State {
  Listed = 'LISTED',
  NoPersonal = 'NO_PERSONAL',
  Personal = 'PERSONAL',
}

export interface User {
  id: ID;
  username: string;
  display_name: string;
  created_at: number;
  avatar_url: string;
  biography: string;
  style: Style;
  emote_sets: EmoteSetElement[];
  editors: Editor[];
  roles: Role[];
  connections: Connection[];
}

export interface Connection {
  id: string;
  platform: string;
  username: string;
  display_name: string;
  linked_at: number;
  emote_capacity: number;
  emote_set_id: null;
  emote_set: EmoteSet;
}

export interface Editor {
  id: ID;
  permissions: number;
  visible: boolean;
  added_at: number;
}

export interface EmoteSetElement {
  id: string;
  name: string;
  flags: number;
  tags: unknown[];
  capacity: number;
}
